css-three-column
aklepper20/c0321-code-solutions pull request #20
Opened 2021-03-13 22:01 UTC by aklepper20

three-column-layout | klepper

![image](https://user-images.githubusercontent.com/77296320/111050953-8588c200-8404-11eb-88a6-113a38c39f55.png)

2021-03-13 22:02 UTC, aklepper20 commented
I believe I am missing a div surrounding the column-third that would pull together the 3 content items inside

2021-03-15 19:51 UTC, codingcodymiller requested changes
Great work so far!!

2021-03-15 19:51 UTC, codingcodymiller commented on css-three-column-layout/styles.css
> +  margin-left: 33%;
That's a lot of margin! What is the purpose of this? If it is to center the image in its container, there are better ways to accomplish this, such as `margin: auto` and flexbox

2021-03-18 22:17 UTC, aklepper20 commented on css-three-column-layout/styles.css
> +  margin-left: 33%;
![image](https://user-images.githubusercontent.com/77296320/111704814-f8c37700-87fc-11eb-824f-dac3801cc62c.png)
margin: auto in da house

2021-03-18 22:26 UTC, codingcodymiller approved these changes
Nice job!!!

2021-03-18 22:28 UTC, merged