Css four column layout
aklepper20/c0321-code-solutions pull request #30
Opened 2021-03-17 04:27 UTC by aklepper20

css-four-layout-column | klepper

![image](https://user-images.githubusercontent.com/77296320/111415054-673df300-869e-11eb-93f0-ec8dfe940e04.png)

2021-03-17 15:52 UTC, codingcodymiller requested changes
Great work so far!! Please see my note.

2021-03-17 15:52 UTC, codingcodymiller commented on css-four-column-layout/styles.css
> +  margin-bottom: -1.5%;
Negative values for margin are a no-no. Try to discover what element has margin or padding that you wanted to reduce here, and just change that measurement to a smaller value.

2021-03-18 07:07 UTC, aklepper20 commented on css-four-column-layout/styles.css
> +  margin-bottom: -1.5%;
![image](https://user-images.githubusercontent.com/77296320/111586238-c161b580-877d-11eb-9ff7-f440a82d1e42.png)
I took out margin-bottom from the div the header lives in

2021-03-18 20:00 UTC, codingcodymiller requested changes
Very nice! One minor fix:

2021-03-18 20:00 UTC, codingcodymiller commented on css-four-column-layout/styles.css
> +  font-weight: ;
Empty property here, this can likely be removed

2021-03-18 21:23 UTC, aklepper20 commented on css-four-column-layout/styles.css
> +  font-weight: ;
![image](https://user-images.githubusercontent.com/77296320/111699513-78e5de80-87f5-11eb-84ab-f3e21b8ebe17.png)
Thank you!

2021-03-18 21:43 UTC, codingcodymiller approved these changes
Great work!!

2021-03-18 22:27 UTC, merged