js bulby
aklepper20/c0321-code-solutions pull request #42
Opened 2021-03-23 23:37 UTC by aklepper20

js-bulb | klepper

![image](https://user-images.githubusercontent.com/77296320/112232549-02cae880-8bf6-11eb-8110-dbfcc7f38e2f.png)

2021-03-23 23:39 UTC, codingcodymiller requested changes

2021-03-23 23:39 UTC, codingcodymiller commented on javascript-light-bulb/main.js
> +    bulbContainer.className = 'bulb-Container';
Your "c" is capitalized in your class name 👀

2021-03-23 23:39 UTC, codingcodymiller commented on javascript-light-bulb/main.js
> +var bulbContainer = 'bulb-container';
These can be removed, they aren't being used

2021-03-24 03:08 UTC, aklepper20 commented on javascript-light-bulb/main.js
> +var bulbContainer = 'bulb-container';
As I pushed it back up to github, js saw this as unused variables as an error and flagged them. I disabled that action in order to make the correct changes. Thank you!

2021-03-24 18:10 UTC, codingcodymiller requested changes

2021-03-24 18:10 UTC, codingcodymiller commented on javascript-light-bulb/main.js
>      bulb.className = 'bulb';
You don't have a variable named `bulb`, you mean `$bulb`, which is the variable holding the DOM element

2021-03-24 18:10 UTC, codingcodymiller commented on javascript-light-bulb/main.js
> +    bulbContainer.className = 'bulb-container';
You don't have a variable named `bulbContainer`, you mean `$bulbContainer`, which is the variable holding the DOM element

2021-03-28 19:03 UTC, aklepper20 commented on javascript-light-bulb/main.js
> +    bulbContainer.className = 'bulb-container';
![image](https://user-images.githubusercontent.com/77296320/112764462-720d5780-8fbd-11eb-9880-2ad01b74e9b1.png)
 Noice

2021-03-29 19:40 UTC, codingcodymiller approved these changes
Nicely done!!

2021-03-30 01:19 UTC, merged