Javascript forms
aklepper20/c0321-code-solutions pull request #47
Opened 2021-03-25 03:28 UTC by aklepper20

js-forms | klepper

![image](https://user-images.githubusercontent.com/77296320/112414437-451c2480-8cdf-11eb-875e-622a9235ee23.png)
![image](https://user-images.githubusercontent.com/77296320/112414530-70067880-8cdf-11eb-8f6e-0989716ad863.png)

2021-03-25 18:21 UTC, codingcodymiller requested changes

2021-03-25 18:21 UTC, codingcodymiller commented on javascript-forms/form-events.js
> +});
Instead of naming these functions in each event handler, you should create them on the global scope, and just pass the function name as a callback

2021-03-26 04:32 UTC, aklepper20 commented on javascript-forms/form-events.js
> +});
![image](https://user-images.githubusercontent.com/77296320/112577482-9f85b580-8db1-11eb-9702-1b2cf844e91e.png)

2021-03-27 00:01 UTC, codingcodymiller approved these changes

2021-03-27 01:43 UTC, merged