completes html-relative-links
aklepper20/c0321-code-solutions pull request #6
Opened 2021-03-09 20:15 UTC by aklepper20

html-relative-links | klepper

![image](https://user-images.githubusercontent.com/77296320/110531980-1e4fd280-80d1-11eb-968c-268b297aa7fe.png)

2021-03-09 20:18 UTC, codingcodymiller requested changes

2021-03-09 20:18 UTC, codingcodymiller commented on html-relative-links/about-me/about-me.html
> +    <li>Contact Us</li>
These still require links

2021-03-09 20:18 UTC, codingcodymiller commented on html-relative-links/contact-us/contact-us.html
> +    <li>Contact Us</li>
These still require links

2021-03-09 20:18 UTC, codingcodymiller commented on html-relative-links/projects/projects.html
> +    <li>Contact Us</li>
These still require links

2021-03-10 21:06 UTC, merged

2021-03-15 03:33 UTC, thebearingedge commented
@aklepper20 Please check out this branch, make a small change, commit, push, and open a new Pull Request so that @codingcodymiller can mark it as completed.